#!/usr/bin/python
# -*- coding: utf-8 -*-

import random
# The numbers that are generated by the random module are not random number they are pseudo-random number by an algorithm. They use the seed to determine the next number.
# But if you set the seed to something and ran twice or more doesn't matter it is more likely you will get the same numbers all the time but it could be and could not be precise as the first time but it will be pretty close all the time.

# random.seed(0)
print(random.random())
# random.seed(0)
print(random.random())

from random import random
# The random function in the random module generates a number between 0.0 < 1.0
print(random())
print(random())
print(random())
from random import seed
# Seed function can set the seed, and then since the seed is changed, it is more likely that number will be same again instead of random.

from random import choice
# The choice function takes a input as a parameter and returns some random value from it.
names = ['Jane','Doe','John','Adam']
number = [x for x in range(5)]
print(choice(names))
print(choice(number))
# More example
for i in range(10):
    print(choice(number))

from random import sample
# This function takes two argument first the data or the sequence and second the number of things to be returned
nums = [x for x in range(10)]
print(sample(nums,3))
# One more thing the number that user is asking to return should not be more than the items length. So for the example above if we say return 11 items it would be invalid and it will return an error. Same with the negative numbers, could not return a negative result.