#!/usr/bin/python
# -*- coding: utf-8 -*-

import random
# The numbers that are generated by the random module are not random number they are pseudo-random number by an algorithm. They use the seed to determine the next number.
# But if you set the seed to something and ran twice or more doesn't matter it is more likely you will get the same numbers all the time but it could be and could not be precise as the first time but it will be pretty close all the time.

random.seed(0)
print(random.random())
random.seed(0)
print(random.random())